#ifndef SSDMMCSTORE_SSDMMC_SIM_INTERNAL_H
#define SSDMMCSTORE_SSDMMC_SIM_INTERNAL_H

#include "ssdmmc_sim.h"

#define SSDMMC_SIM_PAGE_COUNT      1024
#define SSDMMC_SIM_WORD_SIZE       4
#define SSDMMC_SIM_WORDS_PER_PAGE  64

#endif
